version: '3.9'

services:

  # Servicio backend con FastAPI
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    container_name: backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - internal
    logging:
      driver: loki
      options:
       loki-url: "http://loki:3100/loki/api/v1/push"
       loki-external-labels: container=backend,job=fastapi

  # Base de datos PostgreSQL
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: fastapi_db
    networks:
      - internal

  # NGINX como proxy inverso
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - internal
      - public
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: container=nginx,job=nginx

  # Prometheus para métricas
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - internal

  # Grafana para visualización
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - internal

  # Loki para logs
  loki:
    image: grafana/loki:2.9.1
    container_name: loki
    restart: always
    volumes:
      - ./monitoring/loki-config.yml:/etc/loki/local-config.yaml
      - ./monitoring/loki/chunks:/loki/chunks
      - ./monitoring/loki/index:/loki/index
      - ./monitoring/loki/cache:/loki/cache
    command: -config.file=/etc/loki/config.yaml
    ports:
      - "3100:3100"
    networks:
      - internal

volumes:
  pgdata:
  grafana-storage:

networks:
  internal:
    driver: bridge
  public:
    driver: bridge
