name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest bandit trivy

      - name: Lint y seguridad (Bandit)
        run: bandit -r backend

      - name: Pruebas unitarias (simulado)
        run: echo "pytest backend (añadir test si hay tiempo)"

      - name: Escaneo de imagen Docker con Trivy
        run: |
          docker build -t myapp backend
          trivy image --severity HIGH,CRITICAL myapp || true
